#!/usr/bin/env python3
"""Build lib/pocket-qr.js: which essay each Pocket Card links to, plus a QR code for it.

Why: a Pocket Card is a screenshot that travels without the site around it, so it must
carry the way back to the full, certified argument. Each card prints its essay's
address and a real, scannable QR code for it (the old footer was a "SCAN ME" box that
encoded nothing).

The QR images are generated here, not by a CDN library at runtime, so the card works
offline and html2canvas can capture them. Needs `pip install segno`.

Usage: python3 tools/build-pocket-qr.py          (rewrite lib/pocket-qr.js)
       python3 tools/build-pocket-qr.py --check  (fail if it is stale)
"""
import io, json, os, re, sys, base64
import segno

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'lib', 'pocket-qr.js')
BASE = 'https://apologiadaily.com/'

# Pocket-card ids whose essay filename differs from the id (checked against each
# ev-m page's <link rel="canonical">, never guessed from the filename).
ALIAS = {
    'trilemma': 'jesuschar', 'divinity': 'paul-divinity', 'manuscripts': 'manuscript',
    'dna': 'originlife', 'lawsofnature': 'laws', 'trinity_biblical': 'nt_trinity',
    'minimal': 'minimalfacts', 'paul': 'paulconv', 'postresurrection': 'postres',
    'messianic_prophecy': 'messianic-prophecy',
    # 'Evil as Evidence' runs the moral argument's premise 2 (evil presupposes an
    # objective good); library/evil.html is the problem-of-evil essay, which does not.
    'evil': 'moral',
}

def main():
    src = open(os.path.join(ROOT, 'pocket-cards.html'), encoding='utf-8').read()
    cards = re.findall(r"\{ id: '([\w-]+)', title: ?.*?link: ?'([^']*)'", src)
    essay, qr = {}, {}
    for cid, link in cards:
        path = link if link.startswith('library/') else 'library/%s.html' % ALIAS.get(cid, cid)
        if not os.path.exists(os.path.join(ROOT, path)):
            sys.exit('pocket card %r -> %s does not exist' % (cid, path))
        essay[cid] = path
        if path not in qr:
            buf = io.BytesIO()
            segno.make(BASE + path, error='m').save(buf, kind='png', scale=4, border=1,
                                                     dark='#050d1a', light='#ffffff')
            qr[path] = 'data:image/png;base64,' + base64.b64encode(buf.getvalue()).decode()
    body = ('/* GENERATED by tools/build-pocket-qr.py - do not edit by hand.\n'
            '   Pocket-card id -> its full essay, and a QR code for that essay. Plumbing only. */\n'
            'window.POCKET_ESSAY = ' + json.dumps(essay, indent=0, sort_keys=True) + ';\n'
            'window.POCKET_QR = ' + json.dumps(qr, indent=0, sort_keys=True) + ';\n')
    if '--check' in sys.argv:
        cur = open(OUT, encoding='utf-8').read() if os.path.exists(OUT) else ''
        if cur != body:
            sys.exit('lib/pocket-qr.js is stale - run python3 tools/build-pocket-qr.py')
        print('pocket-qr: up to date (%d cards)' % len(essay)); return
    open(OUT, 'w', encoding='utf-8').write(body)
    print('wrote %s: %d cards, %d essays' % (OUT, len(essay), len(qr)))

main()
